### ISSUE TITLE
Docs: please mark parts that are vanilla clearly

### ISSUE THREAD

**Issue by georgehank** [Afforess/Factorio-Stdlib#106]
I found your table module docs, but that's part of vanilla, not of stdlib.  Either mark the whole module as "this is part of vanilla Factorio" or mark (if you extend vanilla) those functions that are vanilla.

**Comment by Nexela** [comment]
Not sure what you are asking for here.  The table library extends the lua
table library and has nothing to do with factorio with the exception of
deepcopy
