### ISSUE TITLE
Force.init() problem

### ISSUE THREAD

**Issue by Martok88** [Afforess/Factorio-Stdlib#123]
I'm attempting to fix the issue in autofill where it [can't be loaded into an existing save.](https://github.com/Nexela/autofill/issues/28) As far as I can tell, Force.init() is not correctly creating the global.forces variable, but I can't figure out why.

**Comment by Nexela** [comment]
It is an event registration order problem

**Comment by Nexela** [comment]
In autofill.  Working on some changes but my time is limited.

**Comment by mickyd** [comment]
so why are we still getting this error 12 months later?
