### ISSUE TITLE
busted test fails, lua 5.3 doesn't have `unpack`

### ISSUE THREAD

**Issue by sparr** [Afforess/Factorio-Stdlib#126]
I'm running lua 5.3 so I get a single failure from `make test`:

```
Error → spec/area/area_spec.lua @ 172
Area should validate area spiral iteration
./stdlib/area/area.lua:412: attempt to call a nil value (global 'unpack')
```

My naive attempt at a fix was to add a line to spec/setup/world.lua:

`if not _G.unpack then _G.unpack = table.unpack end`

This had no apparent effect. That's as far as I got.

**Comment by Afforess** [comment]
Factorio uses Lia 5.21, and so does stdlib. Sorry, 5.3 is unsupported.

**Comment by Nexela** [comment]
Partially re opened.  unpack is deprecated in 5.2.  I will switch stuff  to
table.unpack
