### ISSUE TITLE
Event - revise effect of 'register' with nil handler

### ISSUE THREAD

**Issue by Kovus** [Afforess/Factorio-Stdlib#128]
I'm requesting that Event.register(event, handler) be revised to generate an error upon a `nil` handler, and that a new function be created to remove all handlers associated with a particular event.

At one time, I thought it was a decent idea to be able to remove the events associated with a particular event.  It even seems like something that would be useful to do.

After twice spending more than a short while trying to understand why my event handler isn't working (and in one case, why none of the event handlers associated with an event were firing), I found that both cases were due to me having a typo in Event.register(...).

**Comment by Nexela** [comment]
These issues are handled in the event re write in the data-library branch I
do believe
