### ISSUE TITLE
No GitHub Release for v1.0.2?

### ISSUE THREAD

**Issue by Suprcheese** [Afforess/Factorio-Stdlib#134]
I see that there is a new release in the mod portal, v1.0.2. Now that in Factorio v0.17 you can cross-include mod code, and in 0.17.12 the mod portal will automatically install required dependencies, it seems like a great boon to the Standard Library project.

Yet the most recent [release here on GitHub](https://github.com/Afforess/Factorio-Stdlib/releases) is very old. I know it's just more busywork, but could new releases also be added here?

**Comment by Nexela** [comment]
Soon as I get time I will figure out a better deploy set up that
automatically tags them

**Comment by Nexela** [comment]
Automagic Deploy Script is active! Tags and Releases are now just 1 keypress away
