### ISSUE TITLE
Upgrade Readme and Wiki

### ISSUE THREAD

**Issue by Roang-zero1** [Afforess/Factorio-Stdlib#137]
The logger example in the Wiki is not functional at the moment.
The require line should be `Logger = require 'stdlib/misc/logger'`.

**Comment by Nexela** [comment]
Well, that whole wiki is just.... horribly out of date.......

**Comment by Nexela** [comment]
I have done a lil bit of work To the Readme and Wiki, As well as some fixes to the logger class itself (which have not been released yet)
