### ISSUE TITLE
Wiki with list of functions and their functionalities

### ISSUE THREAD

**Issue by knoxfighter** [Afforess/Factorio-Stdlib#142]
It would be great to have one or multiple wiki-pages, with a list of all the functions this tool provides. So it is easier to find out, if this will be helpful in your mod and what is even possible, without reading the whole sourcecode.

**Comment by Nexela** [comment]
Direct from the readme!

## Documentation

See [the wiki](https://github.com/Afforess/Factorio-Stdlib/wiki) for an introduction and usage/examples.

See the [github pages](http://afforess.github.io/Factorio-Stdlib/) for the latest generated documentation of the Factorio-stdlib

**Comment by knoxfighter** [comment]
Oh, i didnt saw the github page. Thats what i was looking for, thanks
