### ISSUE TITLE
Event.register not passing pattern to function

### ISSUE THREAD

**Issue by DeadlyKitten37** [Afforess/Factorio-Stdlib#157]
#### Describe the Bug

When using Event.register in http://afforess.github.io/Factorio-Stdlib/modules/Event.Event.html 

I tried to use a pattern with out a filter. 
Event.register(defines.events.on_entity_died, onSomethingDestroyed, nil, "died")
Event.register(defines.events.on_player_mined_entity, onSomethingDestroyed, nil , "mined")
Event.register(defines.events.on_robot_mined_entity, onSomethingDestroyed, nil , "mined")

I expected it to pass the pattern to onSomethingDestroyed without trying to filter it, instead it passed nil to the 2nd argument of onSomethingDestroyed

**Comment by Nexela** [comment]
It looks like I should be able to change this allow passing the pattern to the event when the filter isn't used.
