### ISSUE TITLE
Add error (gui) output in case core event registration fails

### ISSUE THREAD

**Issue by mojo2012** [Afforess/Factorio-Stdlib#20]
I just had the problem that a mod tried to access the player inventory on init. This silently failed, letting the on init event handler remain non-functional.

You could add an error(err) to the success condition so the error reason shows up in the gui.

**Comment by Afforess** [comment]
I believe the problem here is that `game` is not accessible when on_init so there isn't a way to handle this error by printing it. What I could do is throw the error the same way factorio does (and let the game crash to menu), which would be an improvement over a silent failure.

**Comment by Afforess** [comment]
This should be fixed in 0.5.0, let me know if you still have issues.
