### ISSUE TITLE
Wrap stdlib in "library"-mod

### ISSUE THREAD

**Issue by mojo2012** [Afforess/Factorio-Stdlib#21]
Hi all,

Currently I'm developing several mods that depend on each other. It's tedious to include stdlib in every mod and keeping it up-to-date. It would be much easier if it would be wrapped in a mod, that could just be included in the info.json and provides all functionality like the bob'S library mod does.

What I'm currently doing is to setup each class I need in the global.* namespace. As I'm still new to lua script's (and factorio's) pitfalls I'm not quite there.

This would help me a lot :-)

**Comment by Choumiko** [comment]
As currently all of stdlibs functions are (mostly) only usefull in control.lua this doesn't really work.
You'd have to expose all functions via a remote interface and in mods that want to use them do something like remote.call("library", "functionToCall", param1, param2, ...)
That's really going to hurt performance (param1, param2 etc are being copied).

Bobs library (afaik) only does stuff in data.lua, where global variables can be/are shared between mods.

**Comment by Afforess** [comment]
Essentially this is not happening for the reasons @Choumiko adds here. Mods can not communicate directly, they have to use a remote interface. Exposing the entire stdlib through this is "Possible" but tedious and would offer essentially no advantage, and several disadvantages:
* Conflicting versions
* Slower / Performance issues
* Error-prone (strings can have typos easily)
