### ISSUE TITLE
Refactor project to be usable as git submodule

### ISSUE THREAD

**Issue by mojo2012** [Afforess/Factorio-Stdlib#22]
Currentl you can't use thos repo as submodule because the lua scripts would not be found, as the "requires" are kind of hardcoded.

would it be possible to move the stuff in stdlib into the root?

**Comment by Afforess** [comment]
Can you be a bit more specific about what you are looking for? You want stdlib/ to become the root directory of the project?

**Comment by mojo2012** [comment]
Sorry, I was in a hurry ;-)

When I include this repo as a git submodule in my mod's root directory, I get:

mojo-ressource-processing
-Factorio-Sdtlib/stdlib
-control.lua
-...

I can "require" stdlib/*.lua in my control.lua file by using: require("Factorio-Stdlib/stdlib/area/chunk.lua"). This will work. But the chunk.lua itself requires just "stdlib/core", which LUA won't find!

I'm not aware of setting the "base path" or anything like to tell LUA to start looking for lua scripts starting from this point.

 Currently I have to move the "stdlib" folder to my root directory. Then all works fine.

But this doesn't allow me to use it as a git submodule :-/

**Comment by OvermindDL1** [comment]
What I generally do is put any submodules in a 'deps' directory then symlink what I need from them to the main project area when things work like that.  Thus just a symlink to ./stdlib from ./deps/Factorio-Stdlib/stdlib works fine, then just store that link in git too.

**Comment by mojo2012** [comment]
The problem is, that windows users then can't checkout my mod.
Currently I play with a friend of mine, and each time we play I ask him to git pull. but that won't work in that case.

**Comment by OvermindDL1** [comment]
They should be able to as long as they are Windows 7 or higher.  NTFS has symlink support in it since then.  If distributed as a zip then no issues regardless as that is packed however your packing script works.

**Comment by mojo2012** [comment]
Ok works quite well :-) you can close this issue. Thanks for the help
