### ISSUE TITLE
New function: find all connected tiles

### ISSUE THREAD

**Issue by mojo2012** [Afforess/Factorio-Stdlib#26]
Hi,

currently I'm working on an improvement to my terraform functionality. Previously when I used the shovel on land it just created a water hole and vice versa.

I'm not very satisfied with this behaviour (where does the water come from? ;-))
So I created a "moat" tile (any better name ideas?).

<img width="378" alt="bildschirmfoto 2016-07-07 um 22 43 17" src="https://cloud.githubusercontent.com/assets/1330361/16669137/38933a84-4494-11e6-8f93-fd3146c90c24.png">

My idea is to flood the all connected moat tiles with water, if on is adjacent to a water tile.
I figure that I could use a lot of loops to go over all moat tiles but there might be a better way?

The perfect solution would be a new functionality in your library ;-) maybe other people need this too.

**Comment by Afforess** [comment]
This *sounds* easy enough, but I need a bit of clarification: what constitutes a connected tile? Does a tile have to be directly North, East, South, or West to be connected. Or can it be a corner tile (NE, SE, NW, SW?)

**Comment by mojo2012** [comment]
As you see in this screenshot, it's not really possible to make conneted tiles in the diagonal directions:
<img width="393" alt="bildschirmfoto 2016-07-13 um 09 07 50" src="https://cloud.githubusercontent.com/assets/1330361/16794636/6d3a1390-48d9-11e6-923c-69002cb3176d.png">

So for now I would stay with N, W, S, E - basically what is visually connected.

**Comment by Afforess** [comment]
Okay, I just added Tile.adjacent, please take a look and see if it fits what you are describing. For your use-case, I imagine you could use this:

```
local connected_tiles = Tile.adjacent(surface, position, false, 'moat')
for _, adj_pos in pairs(connected_tiles) do
   ... do stuff
end
```

**Comment by Afforess** [comment]
@mojo2012 

I've tested out the Tile.adjacent a bit and it seems solid. Just checking in to see if it matches what you were thinking about.

**Comment by Afforess** [comment]
Closing unless @mojo2012 reports any discoveries.

**Comment by mojo2012** [comment]
Sorry, was too busy. I try to report back this week
