### ISSUE TITLE
attempted to index upvalue '_ENV' (a nil value)

### ISSUE THREAD

**Issue by mojo2012** [Afforess/Factorio-Stdlib#27]
The error is being thrown on logger.lua:37

This happens under factorio 0.13 on an old savegame.

Maybe I initialized the logger incorrectly (in on_load)?

**Comment by mojo2012** [comment]
Forget it, I initialized it in the on load event and put it to the global variable. That's probabely not working anymore

**Comment by Afforess** [comment]
The logger object can't be serialized, so yeah, storing it in global won't work.
