### ISSUE TITLE
bug(?) in string.split

### ISSUE THREAD

**Issue by credomane** [Afforess/Factorio-Stdlib#34]
Think I found an bug in the string.split function. If you use a multi-character separator but all the characters of the separator are the same it is treated as a single-character separator.

```lua
local a = string.split("Test the bees knees", "ee")
--Expected {"Test the b", "s kn", "s"}
--Got {"T", "st th", " b", "s kn", "s"}
```

[edit]
Any multi-character separator that start and/or ends with white space behave badly too. :/

Spent way longer than I intended trying to make string.gsub place nice in string.split. I'm just gonna push the php-like explode function from http://lua-users.org/wiki/SplitJoin I've been using for a few weeks now.

**Comment by Afforess** [comment]
Fascinating find.

**Comment by Afforess** [comment]
Added a test case and fixed. Will be part of 0.6.0.
