### ISSUE TITLE
Enhancement request - slight change to options for logger.lua

### ISSUE THREAD

**Issue by Nexela** [Afforess/Factorio-Stdlib#36]
A force append option for those times when you don't want your log starting all over again :)

`local Logger = {mod_name = mod_name, log_name = log_name, debug_mode = debug_mode, buffer = {}, last_written = 0}

    --- Logger options
    Logger.options = {
        log_ticks = options.log_ticks or false, -- whether to add the ticks in the timestamp, default false
        file_extension = options.file_extension or 'log', -- extension of the file, default: log
		force_append = options.force_append or false, -- append the file on first write, default: false
    }
    Logger.file_name = 'logs/' .. Logger.mod_name .. '/' .. Logger.log_name .. '.' .. Logger.options.file_extension
	Logger.ever_written = Logger.options.force_append`

**Comment by Afforess** [comment]
Good idea, included for the next release.
