### ISSUE TITLE
Test failures on WIndows

### ISSUE THREAD

**Issue by AndyBursh** [Afforess/Factorio-Stdlib#43]
Hi Afforess and contributors,

I just began to set up my environment in order to send you a pull request down the line, and my first port of call was to run the tests. Unfortunately, it looks like there are 3 broken.

```
Error spec\area\chunk_spec.lua @ 5
Chunk Spec should give the correct chunk coordinates for a position
.\stdlib/area/chunk.lua:20: attempt to index global 'bit32' (a nil value)

Error spec\area\tile_spec.lua @ 34
Tile Spec should ensure indexes are stable and deterministic
.\stdlib/area/tile.lua:120: attempt to index global 'bit32' (a nil value)

Error spec\area\tile_spec.lua @ 49
Tile Spec should verify getting and setting data
.\stdlib/area/chunk.lua:20: attempt to index global 'bit32' (a nil value)
```

I'm running Windows 10, and I've installed the `busted` and `bit32` packages (and their dependencies) through LuaRocks, having allowed it to install a version of Lua for me.

Are these test failures a result of something missing in my environment, or are they genuine test failures? (I suspect the former, but I thought it better to ask)

Regards,
Andy

**Comment by Afforess** [comment]
bit32 was introduced in lua 5.2 (which is what Factorio uses). You are likely running Lua 5.1
