### ISSUE TITLE
Merge?

### ISSUE THREAD

**Issue by sebopop** [Afforess/Factorio-Stdlib#45]
Hi!

I just posted this on the Factorio forums: [https://forums.factorio.com/viewtopic.php?f=34&t=31980](url)
I'd gladly contribute and merge under some conditions :)
BTW I know it's bad, i coded in a hurry

Regards.

**Comment by Afforess** [comment]
If you have code written, you can open pull requests and contribute to the stdlib. Please make sure you document and look at how the tests here work, I want to try to keep code quality high, so modders can ensure that the stdlib won't be a source of bugs.

I looked over your list and it looked interesting. I've implemented AStar* in Lua already for a separate mod, Misanthrope, and have not had enough interest to port it here. You are free to take a look at that too.

I look forward to your contributions!
