### ISSUE TITLE
0.14 change "broke" Game.print_all()

### ISSUE THREAD

**Issue by credomane** [Afforess/Factorio-Stdlib#49]
Due to Game.print_all checking player.connected any mod that uses stdlib in their on_init or on_configuration_changed handlers will show player.connected as always false in single player only.

See https://forums.factorio.com/33208 for the full details.

**Comment by Afforess** [comment]
Fantastic. Not sure how to safely tell if the player can be used to print out a message then...

**Comment by credomane** [comment]
My understanding from rseding91 is if you get an error when `anything.valid == true` then it is extremely likely a factorio bug.

So I did some experimenting. I can print to offline players without errors and they will actually see any messages sent to them while offline in their console/chat history when they return too. I can actually do anything I want to an offline player as if they were online. So it would seem to me that you and I both do more validation checking than "required" in Factorio. :P

**Comment by Afforess** [comment]
>So it would seem to me that you and I both do more validation checking than "required" in Factorio.

Given inconsistency in the past, I always err on the side of safety.
