### ISSUE TITLE
Improve train library to work with any locomotive, not just vanilla diesel locomotive

### ISSUE THREAD

**Issue by Afforess** [Afforess/Factorio-Stdlib#53]
Currently the trains library only watches for events on the [vanilla diesel locomotive](https://github.com/Afforess/Factorio-Stdlib/blob/master/stdlib/trains/trains.lua#L218), but it should be possible to extend this to check for any type of locomotive.

**Comment by AndyBursh** [comment]
This shouldn't be too difficult to do. Something like the below would be my proposed solution.

```
-- Use an array to support multiple types
Trains.settings.locomotive_types= {'diesel-locomotive', 'farl'}

local function filter_event(event_parameter, callback)
    return function(evt)
        for _, entity_type in pairs(Trains.settings.locomotive_types) do
            if(evt[event_parameter].name == entity_type) then
                callback(evt[event_parameter])
            end
        end
    end
end

Event.register(defines.events.on_entity_died, filter_event('entity', Trains._on_locomotive_changed))
```

Since `Trains.find_filtered` more or less passes its input directly to `Surface.find_all_entities`, you can already search for different types of locomotives in the same way you would when using that module.

**Comment by Afforess** [comment]
@AndyBursh admittedly I don't have the Factorio prototypes in front of me, but isn't there only one `type` of entity that can be a train, the diesel locomotive? I believe the FARL train, or electric trains I seem to recall in some other mod, do have different entity names, but the entity type should still be diesel locomotive (or whatever type they all share). Couldn't we filter based on type and make this even easier?

**Comment by AndyBursh** [comment]
I would be lying if I said I knew much about that. I'll have to do some investigation.

**Comment by Choumiko** [comment]
Yes, they all have type locomotive. That would have been my first PR once i would have found the time to do anything xD
