### ISSUE TITLE
petrify( entity, mode )

### ISSUE THREAD

**Issue by aubergine10** [Afforess/Factorio-Stdlib#54]
I've been using this function a lot in my mods, maybe it would be useful for StdLib with some extra tweaks?

```lua
local function petrify( entity, mode )
  mode = mode == false and true or false
  entity.active    = mode
  entity.operable  = mode
  entity.rotatable = mode
end
```

Usage:

```lua
petrify( someEntity ) -- petrify it
petrify( someEntity, false ) -- reanimate it
```

**Comment by Afforess** [comment]
Sure, I bet there are a lot of similar low-hanging fruit for entities.

**Comment by Afforess** [comment]
@aubergine10 thoughts on whether `petrify` should include minable and destructible as fields to set too?

**Comment by aubergine10** [comment]
Hmm.. I feel they are two distinct use cases:

* "Don't let player change entity", and/or
* "Don't let player remove entity"

There is, however, obvious cases where there will be overlap. So I'm not really sure what best approach is here.

**Comment by Afforess** [comment]
So maybe a `set_indestructible` as well?

**Comment by aubergine10** [comment]
It'll make code more semantic, not to mention the error checking that's bundled with stdlib functions, so yes IMO it's worth adding.

**Comment by Afforess** [comment]
Alright, I've implemented `Entity.set_industructible` as well.
