### ISSUE TITLE
Trains module results in nil reference. [0.7.0]

### ISSUE THREAD

**Issue by nullvoid8** [Afforess/Factorio-Stdlib#62]
Loading the trains module in my control.lua causes the following error.
````
**__ElephantTrains__/control.lua:8:
  __ElephantTrains__/stdlib/surface.lua:22: 
  attempt to index global 'game' (a nil value)**
````

I have tracked this down to line 235 of Trains.lua (`Trains._registry = create_train_registry()`)
since this line runs at the top level, `game` is indeed not in scope, so the eventual call to `Surface.find_all_entities` and so on fails.

**Comment by Afforess** [comment]
Thanks for the report. I'll write up a test case to reproduce, and follow up with a bug fix.

**Comment by Afforess** [comment]
@nullvoid8 can you try the latest code pushed to the master branch, and verify your issue is resolved? If so, I will release a bug-fix release.

**Comment by nullvoid8** [comment]
@Afforess I can confirm that this issue is fixed.

**Comment by Afforess** [comment]
Good to hear!
