### ISSUE TITLE
trains.lua - unusable in MP/other bugs

### ISSUE THREAD

**Issue by Nexela** [Afforess/Factorio-Stdlib#68]
First: And most important is the potential for desyncs
Event.core_events.init, function() Trains._registry = create_train_registry() end

Trains._registry is not saved into the global table leading to desyncs.
Player 1 creates game, init is called and scans trains now the Trains variable contains extra data
Player 2 joins and since this is MP init is not triggered for player 2 and he does not have the extra data
script does something with trains. 2 different things happen. game goes kaboom.

Haven't tested yet but replacing Trains._register with global._trains seems like the easiest approach

Second: function local function create_train_registry() Only scans surface 1  
Should be changed to loop through all surfaces in case multiple surface trains are present.

**Comment by Nexela** [comment]
Third the events look like they are using the name and not the type. if that is the case this wouldn't work for mod added trains.

**Comment by Afforess** [comment]
@Nexela I moved the train registry to global and updated the events to filter on the `locomotive` type rather than `diesel-locomotive` entity name.

I think a bit more robust logic for surfaces is needed beyond what you've proposed, as surfaces could be created (or destroyed) mid-game. I need to look into this further.

However at a minimum, the critical issues *should* be resolved, if you want to test with the latest codebase.

**Comment by Nexela** [comment]
I wouldn't spend too much time on this until .15
It has been confirmed base game will have more train related events

**Comment by Nexela** [comment]
> I think a bit more robust logic for surfaces is needed beyond what you've proposed, as surfaces could be created (or destroyed) mid-game. I need to look into this further.

That part is fine, factorio handles cleanup  as long as .valid is checked before doing anything. The train will cease to exists if the surface does.  Of course storing per surface would also add the overhead that now you might as well store per force, and open up a whole nother can of worms.

**Comment by Nexela** [comment]
global._registry seems too ambiguous  As no other modules seem to use this global._trains would be a better choice

**Comment by Afforess** [comment]
@Nexela Fair point about the naming.

**Comment by Afforess** [comment]
I updated stdlib to register trains on any surfaces. I think that covers everything you've raised - if you find more, open another issue.
