### ISSUE TITLE
Would it be useful to have generic placeholder images?

### ISSUE THREAD

**Issue by nathanmerrill** [Afforess/Factorio-Stdlib#69]
If you guys would include it in the repo, I'd totally make a bunch of generic placeholder images.  They'd basically be A-Z with borders around them.

Is this in scope of Factorio-Stdlib?

**Comment by Afforess** [comment]
I'm a bit lost, can you give a practical example of what sort of images you think would be useful?

**Comment by nathanmerrill** [comment]
These would simply be a letter with a border. The point would be to allow for easy selection of a placeholder, and the letters allow for differentiation

**Comment by OvermindDL1** [comment]
Except that since this library is copied into each mod, then each mod would have a copy of the files...  It seems like needless additions?  Would probably be better as a mod?

**Comment by nathanmerrill** [comment]
Yeah, that could work.  It sounds like it is out of scope, so I'll post it as a mod.
