### ISSUE TITLE
Overall enhancements/optimizations

### ISSUE THREAD

**Issue by Nexela** [Afforess/Factorio-Stdlib#70]
I am halfway through a code cleanup on stdlib.

The biggest part of the cleanup is making sure everything lints cleanly in a very strict linting environment. This includes use of locals for performance and standard reasons.

Right now I have to ignore most of stdlib and that just doesn't feel right.
https://gist.github.com/Nexela/05a8fa5164ae107f599c2295935ff906

So far everything I have done is mostly backwards the only thing that changes is the way some modules are added.

Invalid:   `require("stdlib/area/area")`
required: `local Area = require("stdlib/area/area")`

Other examples that would work but are not recomended:

- `Area = require("stdlib/area/area") --Makes Area global `
- `local MyArea = require("stdlib/area/area") -- Works but no reason to do it this way`
- `MyArea = require("stdlib/area/area") -- Globals are bad mkay, also no reason to change identifier`

The next on my list Event/Gui  those will require more thinking on though as simply making Event local will break things.

If you are interested in a PR on this when it is done/in progress let me know.

**Comment by Afforess** [comment]
I'm definitely interested.
