### ISSUE TITLE
global._trains_registry, global._surface_time

### ISSUE THREAD

**Issue by Nexela** [Afforess/Factorio-Stdlib#72]
In train init will not be called if if stdlib/trains is added after the mod has been installed
Additionally even init is not going to be reliable in instances where mod authors do this

require("stdlib/event")
local trains = require("train")
Event.register(Event.core_events.init, function() global = {})

During init trains will be inited first, followed by the top level init which overwrites the global

Doing global = {} is bad practice though.

As for Time changing global. at the top is not recommended but will work.  However issues will still happen if mod is updated mid game to use Time the global will be discarded in on_load for the version saved in the map which won't have _surface_time. leading to errors

Time will be addressed in the upcoming pull request.

Looking through trains It needs an overhaul to use surface/force.get_trains so I am not going to mess with ti too much

**Comment by Afforess** [comment]
I have local changes for the surface.get_trains changes. If you want to tackle the Time changes, I can focus on the Trains changes.

**Comment by Nexela** [comment]
I put in a request for unique id on trains.  Hopefully I hear back soon
https://forums.factorio.com/viewtopic.php?f=28&t=45539&p=262039#p262039
