### ISSUE TITLE
Enhancement - Force CRC check as Event option

### ISSUE THREAD

**Issue by Nexela** [Afforess/Factorio-Stdlib#74]
In order to help track down user desync problems being able to force a CRC check after every handler is called might be a big help

Example ->
Event.force_crc_check = true

When iterating handles before calling them
game.print("forcing CRC check handler)
game.force_crc()

Doing something like this can help the user narrow down desync problems in their code.

**Comment by Afforess** [comment]
Not a bad idea, although _every_ event might be excessive. I imagine recalculating the crc for each tick would slow the game down to a crawl - nevermind events that occur many times a tick.

**Comment by Nexela** [comment]
This would essentially be a debug flag only (for finding desyncs)  right now CRC checks happen at the end of every tick automatically this would just force them to happen between events.  

Doing it this way will print a message with details of the event being called ID ect, If there is a desync message after it Then you know which of your events the user error is in :)
