### ISSUE TITLE
Gui new events

### ISSUE THREAD

**Issue by Nexela** [Afforess/Factorio-Stdlib#75]
Needs expansion to include the two new events:
on_gui_elem_changed
on_gui_selection_state_changed

Additionally stdlib/gui/gui would make more sense as stdlib/event/gui.  What are your thoughts on this?

**Comment by Afforess** [comment]
Yes, and you can relocate as long as you leave a stub module in `stdlib/event/gui` which just has `require 'stdlib.gui.gui` and a deprecation notice.
