### ISSUE TITLE
keybind events and Event.register

### ISSUE THREAD

**Issue by Nexela** [Afforess/Factorio-Stdlib#76]
Currently there is no way to register keybind events with stdlib/event/event

These events are passed as literal strings which are internally turned into a script id number.  The only way I see to get the id number is from the raised event  however the raised event also contains the keybind name.  I can pester Klonan about this some more but I need a compelling argument for it.

**Comment by Afforess** [comment]
It would probably be better to create a separate module then - `Keybind` and register them separately.

**Comment by Nexela** [comment]
The simplicity of this didn't warrant a separate file.
