### ISSUE TITLE
util module

### ISSUE THREAD

**Issue by Choumiko** [Afforess/Factorio-Stdlib#8]
I just realised i have a few small functions i use across mods that are not necessarily restricted to something Factorio specific, e.g.
```lua
function trim(s)
  return (s:gsub("^%s*(.-)%s*$", "%1"))
end
function round(num, idp)
  local mult = 10^(idp or 0)
  return math.floor(num * mult + 0.5) / mult
end
function isEmpty(tableA)
  if tableA ~= nil then
    return next(tableA) == nil
  end
  return true
end
```
Would a util module make sense? It could get out of hand rather quick i guess.
Right now i'm thinking something like
```lua
util.string.trim(s)
util.string.starts_with(s, needle)
util.string.ends_with(s, needle)

util.math.round(num, idp)

util.table.is_empty(table_)
```
should work for a start. If it get's too much it can be moved to a own module.

**Comment by Afforess** [comment]
I think you could even add the functions directly to the metatables of the classes they best fit with. So you could add trim, starts_with, etc to the string class by updating the metatable.

**Comment by Afforess** [comment]
I implemented the string.trim, string.starts_with and string.ends_with (the latter two are stolen from http://lua-users.org/wiki/StringRecipes ) and associated tests. Anyone is free to contribute the others.

**Comment by Afforess** [comment]
I think we've since added lots of new utility functions in `string`, `table`, and various other modules. The goals for the issue are completed, but contributors are free to submit PRs for more utility code.
