### ISSUE TITLE
Algorithm to determine the extend of ore patches

### ISSUE THREAD

**Issue by Pandemoneus** [Afforess/Factorio-Stdlib#80]
I would like to see a function/algorithm added, that can, given a single ore entity from an ore patch, return all (connected) ore entities of an ore patch. This could be extended to place a bounding box around the ore patch. I will code a first version and make a pull request.

**Comment by Afforess** [comment]
Definitely sounds like a useful feature. Go for it.

**Comment by Nexela** [comment]
I agree on it being usefull

Some things to think about.
What defines an ore patch, if there is a gap of XXX tiles is it still part of the same patch?
What if the patch is a combined patch with say coal/iron etc etc.

Probably the best fit for it would be stdlib/entity/resource.lua

I am currently (very slowly) writing a data stage Prototype module.  As well as a player/force/surface event module

**Comment by Choumiko** [comment]
> What defines an ore patch, if there is a gap of XXX tiles is it still part of the same patch?
What if the patch is a combined patch with say coal/iron etc etc.

My definition of an ore patch: Connected in the 4 main directions + 4 diagonals, no gaps and one single ressource.
Can't remember a case where i'd see 2 copper patches close enough together to consider them 1 patch. 

Probably worth checking out https://github.com/narc0tiq/YARM When i used it back in the days it always marked what i would have expected.

**Comment by Afforess** [comment]
YARM has a compatible license so if any code is reused there, we just need to attribute it in the file.

**Comment by Afforess** [comment]
Need any help @Pandemoneus? I've contributed a bit to YARM myself and it sounds like the others are interested too.

**Comment by Pandemoneus** [comment]
Alright, haven't had time working on it yet, but I will start now. I've asked Rseding whether he could expose what they use for the Factorio minimap on ore patches, but he redirected me to one of his older mods, namely Landfill: https://mods.factorio.com/mods/Rseding91/Landfill

I'll see that I can get a first version up, I am sure there will be possible performance improvements.

**Comment by Pandemoneus** [comment]
Alright, got the first version for resource scanning up: https://github.com/Pandemoneus/Factorio-Stdlib/commit/961e046bed026e83295d28dfbddb8a3904174887

**Comment by Nexela** [comment]
return resource_at_tile[1] -- there should never be another resource at the exact same coordinates
There can be more than one resource on a tile,

**Comment by Nexela** [comment]
Also, if you do it as a pull request it becomes a lot easier to make review comments :)

**Comment by Pandemoneus** [comment]
Alright. Under which circumstances can there be more than one resource on a tile? I took that code from YARM.

**Comment by Nexela** [comment]
Its rare but it does happen in vanilla, additionally mods can "stack" them

**Comment by Pandemoneus** [comment]
Resource (patch) detection and getting the bounding box are now in as of https://github.com/Afforess/Factorio-Stdlib/pull/93.
