### ISSUE TITLE
Module documentation doesn't mention required imports

### ISSUE THREAD

**Issue by dustine** [Afforess/Factorio-Stdlib#85]
This is very small issue, if you could even call it that, but there's no mention to what lua file each module corresponds to in the documentation. *This is more relevant on submodules*, like `Position` (in `stdlib/area`) or `Time` (`stdlib/events`).

As in, right now on the header of the `Area` module you have:
![image](https://cloud.githubusercontent.com/assets/8994495/26337622/e5b69c96-3f71-11e7-8db9-c6f5d18a77a7.png)
when, for lua beginners or people like me that don't want to go check the directory tree every time they want to import something, it could instead be like this:
![image](https://cloud.githubusercontent.com/assets/8994495/26337709/ad7998aa-3f72-11e7-850a-3a5d2dd74572.png)

Doesn't have to have this formatting, or even be there, maybe a more fitting place for this would be the index page. Thank you for your time! 😄

**Comment by dustine** [comment]
And probably as an example on how much this is needed, I forgot the right syntax on lua is `require`, not `import`. Whoops 😳

**Comment by Nexela** [comment]
I will have this done in the document changes I am working on :)

**Comment by Afforess** [comment]
Implemented in #83
