### ISSUE TITLE
Doing some work on events system have. Why the forced return from events?

### ISSUE THREAD

**Issue by Nexela** [Afforess/Factorio-Stdlib#87]
it('.dispatch should abort if a handler returns true', function()

This actually bit me so many times before I realized it.

Is there any special reason this is needed?

**Comment by Afforess** [comment]
The idea was to be able to end processing of an event early, useful if you have multiple handlers and don't want the later ones to proceed. I'm not sure how often it has been used, I don't think I ever ended up using it.

If we still want to support this functionality, maybe we could add a `.valid` field to the event object, and setting `event.valid = false` would disable further propagation. Or maybe it's not useful enough to warrant the work.

**Comment by Nexela** [comment]
I will add event.stop_processing  read to cancel
