### ISSUE TITLE
Minor Event again

### ISSUE THREAD

**Issue by Nexela** [Afforess/Factorio-Stdlib#91]
Putting here as a reminder for me to fix this weekend.
Event.dispatch dispatches incorrectly if the event has input_name from a previous event.
to fix check name and _registry before input_name

**Comment by Afforess** [comment]
I only just now even noticed the `input_name` field. What was the goal with this?

**Comment by Nexela** [comment]
Related #76

Registering a keybind doesn't associate the keybind with the int id so it has to be grabbed when the event is dispatched

This bug only shows up in rare cases where the event data from a keybind is forwarded to another event handler.  Solution is to check name before event. I have the fix all set and everything seems to be working like it is supposed to just need to get around to cherry picking it into a hotfix :)
```lua
    if event then
        local _registry = event.name and Event._registry[event.name] or event.input_name and Event._registry[event.input_name]
        if _registry then
            local force_crc = Event.force_crc
            for idx, handler in ipairs(_registry) do
```

**Comment by Afforess** [comment]
Alright, that makes sense. I haven't played with keybindings, but I follow what the issue is now.
