### ISSUE TITLE
Surface.lookup does not accept a LuaSurface

### ISSUE THREAD

**Issue by Pandemoneus** [Afforess/Factorio-Stdlib#95]
Contrary to the LuaDoc, Surface.lookup does not accept a single LuaSurface object. It has to be in a table to work. There is no test for this special case either.

**Comment by Pandemoneus** [comment]
Wait, I made a mistake. When I use the surface from the following code snippet, the Surface.lookup does not work:
```
script.on_event(defines.events.on_built_entity, function(event)
  if event.created_entity.name ~= 'resource-monitor' then return end

  local player = game.players[event.player_index]
  local pos = event.created_entity.position
  local surface = event.created_entity.surface

  local resource = Resource.get_resource_at(surface, pos)
end)
```

**Comment by Afforess** [comment]
Fixed as of https://github.com/Afforess/Factorio-Stdlib/commit/fa768b45754684fd2d7d2c048e69020db283ebbc

**Comment by Afforess** [comment]
As a note, @Nexela, as to why your unit test did not catch this, despite explicitly testing it, see my commit: https://github.com/Afforess/Factorio-Stdlib/commit/7446da88a7f9e0feb5d21f55e061673d26cbd701

The tl;dr is that your `pairs` iteration of the table object would reach the `'name'` field on the object, and the second string lookup would work. Factorio LuaSurfaces have no such `'name'` fields, so the difference between your mocked object and the game object caused the test to inaccurately succeed. Using a metatable to hide the field from `pairs` reproduced the issue.
