### ISSUE TITLE
ldoc documentation look & feel changes

### ISSUE THREAD

**Issue by trappi-stone** [Afforess/Factorio-Stdlib#98]
Made some changes to the look & feel of the ldoc documentation website.

https://trappi-stone.github.io/Factorio-Stdlib/

I'm not sure how this repository handles the Github pages for the documentation, but my fork uses the master's docs folder to retrieve index.html.

Basically, I renamed doc folder to docs, and added three files:

1. config.ld
2. ldoc.css
3. ldoc.ltp

To generate the ldoc documentation, I go into the docs folder from the console and just enter ldoc followed by a period: `ldoc .`

**Comment by trappi-stone** [comment]
The Github pages link above might not work for a while until I get the repository set up properly on my fork. I've been putting in some effort into improving the look & feel of the documentation site. Also, there seem to be a few consistencies in the way the types were used in stdlib's Lua code; for example, LuaBoundingBox is displayed as a type of the parameters to some functions. However, I believe it would be nice to instead, display as just `BoundingBox`. Also, I'd like to hear what you think about standarding the way to write the types for the `tparam`, `treturn`, `see`, etc. tags. So, just as an example, `@tparam api.LuaEntity <param_name> <param_description>` instead of `@tparam LuaEntity <param_name> <param_description>`. My fork already has the `config.ld` and necessary code to address the above proposed idea. I'll get back to you about this for a further discussion in the near future.

**Comment by trappi-stone** [comment]
Actually, I think it's better to post this here... I am trying to get CircleCI to generate the documentation page, but I've been constantly running into some problems... 

Here is the link to my CircleCI build attempts: https://circleci.com/gh/trappi-stone/Factorio-Stdlib/tree/doc-changes

I keep running into the following error:

```
...
Copying Files
Auto Generating with ldoc
ldoc: missing required parameter: file

ldoc, a documentation generator for Lua, vs 1.4.6
  -d,--dir (default doc) output directory
  -o,--output  (default 'index') output name
  -v,--verbose          verbose
...
```

**Comment by trappi-stone** [comment]
Okay, I resolved the CircleCI issue that I was running into (described in the previous comment). I'm able to move forward with some changes on my fork now. @Nexela thank you for pointing out that ".api" being unnecessary, I agree with you on that. I have removed the prefix detection in config.ld and ldoc.ltp.

**Comment by Afforess** [comment]
Nice work, the documentation changes are a definite improvement. Are you still tweaking things, or do you want to open a PR with the changes so far?

**Comment by trappi-stone** [comment]
It certainly is a revamp. Went through a couple of rounds of reviews from @Nexela and from a couple of others, but I am still making updates. I would like to wrap this up before the end of the day. My thought was to squash all the commits and then perform a pull request for final reviews. Did you have anything else in mind in regards to the approach I should take once I'm done wrapping this up?

**Comment by trappi-stone** [comment]
I noticed that when there is a parameter or a return value which is allowed to be of any type, some doc pages showed **T** and some showed **Mixed**. Should we represent **all** of them as **T** instead?

**Trains module**

What do you think about having [on_train_id_changed](https://trappi-stone.github.io/Factorio-Stdlib/modules/Trains.html#on_train_id_changed) & [_on_locomotive_changed](https://trappi-stone.github.io/Factorio-Stdlib/modules/Trains.html#_on_locomotive_changed) under the [Events](https://trappi-stone.github.io/Factorio-Stdlib/modules/Trains.html#Events) section? does it make sense to place them in a separate section? I have rearranged them a little bit in that way; you may view the doc if interested.

[find_filtered](https://trappi-stone.github.io/Factorio-Stdlib/modules/Trains.html#find_filtered) function has a slightly confusing description. Specifically, the two sentences that describe how the function behaves when the user does not supply `criteria.surface`. However, I have not read through the code hard enough to understand the correct behavior of the function in that situation.

Is the [criteria table](https://trappi-stone.github.io/Factorio-Stdlib/modules/Trains.html#criteria) set up correctly?

**Comment by Nexela** [comment]
> I noticed that when there is a parameter or a return value which is allowed to be of any type, some doc pages showed T and some showed Mixed. Should we represent all of them as T instead?

do you have an example?

**Comment by trappi-stone** [comment]
The usage of "T": http://afforess.github.io/Factorio-Stdlib/modules/Queue.html#push_left
The usage of "Mixed": http://afforess.github.io/Factorio-Stdlib/modules/Trains.html#set_data

**Comment by Nexela** [comment]
Mixed

Also Queue should be linking to itself.

**Comment by trappi-stone** [comment]
I have decided to do more reviews throughout this upcoming week. I will make a pull request in the very near future. However, in the meantime, I would appreciate it if @Afforess, @Nexela, and others continue to give me further inputs (whenever the time allows) to even minor issues or even the smallest look&feel changes on the updated website. I still have some questions in my previous comments that have not been answered, but I'll continue to move forward with what I got that pertains to the questions if I don't get any replies to them.

For reference purposes...

Updated doc website: https://trappi-stone.github.io/Factorio-Stdlib/
Current doc website: http://afforess.github.io/Factorio-Stdlib/index.html

**Comment by Nexela** [comment]
I will look into your find_entities questions tomorrow.  I plan on doing Metatable conversions to chunk, tile, and surface.

**Comment by Afforess** [comment]
Squashing the commits is definitely nicer, but not a firm requirement. (I don't get enough contributions to make it worth having firm standards, I'll take all.)

I'm happy with the documentation, but I agree with @Nexela that _mixed_ is more clear than "T" in what the type of data should be.

The first part of `find_filtered`'s description for what occurs when a surface is not specified is correct. When no surface is supplied, all the surfaces are iterated.

**Comment by trappi-stone** [comment]
On the updated [doc website's Queue module](https://trappi-stone.github.io/Factorio-Stdlib/modules/Queue.html):
* The return descriptions now show **Mixed**, and I have replaced **T** with **Mixed** on the other pages as well.
* Queue is now linking to itself.


There are a couple of other modules on the current website ([Event](http://afforess.github.io/Factorio-Stdlib/modules/Event.html) & [Event.Gui](http://afforess.github.io/Factorio-Stdlib/modules/Event.Gui.html)) that do not link to themselves on their return descriptions. Now, the updated website's [Event](https://trappi-stone.github.io/Factorio-Stdlib/modules/Event.html) module is linking to itself. However, for the [Event.Gui](https://trappi-stone.github.io/Factorio-Stdlib/modules/Event.Gui.html) module, I am not quite sure if I should have approached it in the way that I did. I had Event.Gui to link to itself on its functions' return descriptions, but the Gui object was a slightly different story. The Gui object did not have its own module page; therefore, I wrote some ldoc comments to represent the Gui object as a table. Representing Gui as a table allowed me to link to it from the Gui functions' return descriptions.

> Squashing the commits is definitely nicer, but not a firm requirement. (I don't get enough contributions to make it worth having firm standards, I'll take all.)

I generally heard that many repository maintainers prefer the pull requests squashed. Also, I myself don't like myself performing so many minor commits which clutter up the commit history (unavoidable in many situations though), although I wouldn't mind contributors **not** squashing either if I was maintaining a relatively small repository. Having that said, I think I'll try squashing anyway.

> The first part of `find_filtered`'s description for what occurs when a surface is not specified is correct. When no surface is supplied, all the surfaces are iterated.

I see, okay, then I can safely rule that particular statement out from a further review.

**Comment by trappi-stone** [comment]
#99

**Comment by trappi-stone** [comment]
My updates were pulled by Nexela into his player-force branch. Closing this discussion.
